name = "supervendas"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "vendas_pro"
database_id = "102413e6-5a14-4668-97e9-4a66ad5e58ea"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "vendas-pro-backups"

[vars]
# Coloque como Secret:
# wrangler secret put JWT_SECRET
